
import { OnomatopoeiaWord, Category } from './types';

export const MASCOT_COMMENTS = [
  "I'm *buzzing* with excitement for your next answer!",
  "Can I get a *drumroll* please? ... *Brrrm-tsching!*",
  "That logic *clicked* instantly!",
  "Don't *mumble*, shout your answer with pride!",
  "You are absolutely *booming* with knowledge today.",
  "*Snap!* That was fast.",
  "I *chews* you to solve this one! *Crunch!*",
  "*Ding!* *Ding!* We have a winner!",
  "Don't *croak* under the pressure, you got this.",
  "I heard a *rustle*... is that your brain gears turning?",
  "*Sizzle!* You are on fire!",
  "Make a *splash* with the correct choice.",
  "*Zoom*! You're speeding through these.",
  "No need to *whine*, just try again!",
  "*Zap!* Right on target.",
  "I'm *purring* with delight at your progress.",
  "It's *crunch* time! Let's do this.",
  "*Gulp*... that looked tricky, but you nailed it.",
  "Don't let the answer *whoosh* over your head.",
  "*Honk* if you love grammar!",
  "*Plop* goes the wrong answer... oops!",
  "*Clap* your hands for that performance!",
  "I *whisk* you the best of luck! *Swish!*",
  "*Pop* quiz! Just kidding, take your time.",
  "That answer really *rang* true.",
  "Stop *babbling* and start answering!",
  "*Thud*... that one landed solidly.",
  "I'm *gurgling* with pride right now.",
  "*Hiss*tory in the making with these scores!",
  "Don't *squeak* by, aim for a high score!",
  "*Bang!* You nailed it.",
  "Feeling *chirpy* today, aren't we?",
  "*Slurp* up all that knowledge!"
];

export const ONOMATOPOEIA_DATA: OnomatopoeiaWord[] = [
  // Animal Noises
  { id: 1, word: "Arf", meaning: "The sound of a dog, particularly a small dog.", example: "The puppy let out an excited arf as its owner approached.", category: Category.ANIMALS },
  { id: 2, word: "Baa", meaning: "The sound made by a sheep.", example: "The sheep baaed loudly in the pasture.", category: Category.ANIMALS },
  { id: 3, word: "Bark", meaning: "The sharp sound made by a dog.", example: "The dog barked at the mailman.", category: Category.ANIMALS },
  { id: 4, word: "Bleat", meaning: "The sound made by a sheep, goat, or calf.", example: "The goat bleated for more food.", category: Category.ANIMALS },
  { id: 5, word: "Bow-wow", meaning: "The sound of a dog, typically used humorously or by children.", example: "The children laughed at the dog's loud bow-wow.", category: Category.ANIMALS },
  { id: 6, word: "Cackle", meaning: "A harsh, shrill laugh.", example: "The witch's cackle echoed through the night.", category: Category.ANIMALS },
  { id: 7, word: "Caw", meaning: "The harsh cry of a crow.", example: "The crow cawed from the treetop.", category: Category.ANIMALS },
  { id: 8, word: "Cheep", meaning: "A short, weak chirp, like that of a baby bird.", example: "The chicks cheeped for their mother.", category: Category.ANIMALS },
  { id: 9, word: "Chirp", meaning: "A short, sharp sound made by small birds or insects.", example: "The crickets chirped in the evening.", category: Category.ANIMALS },
  { id: 10, word: "Chirrup", meaning: "A series of chirping sounds.", example: "The birds chirruped cheerfully in the morning.", category: Category.ANIMALS },
  { id: 11, word: "Chitter", meaning: "A rapid series of short, high-pitched sounds.", example: "The squirrel chittered as it ran up the tree.", category: Category.ANIMALS },
  { id: 12, word: "Chitter-chatter", meaning: "Idle talk or chatter.", example: "The chitter-chatter of the students filled the classroom.", category: Category.ANIMALS },
  { id: 13, word: "Chitty", meaning: "A soft, rapid sound.", example: "The birds made a chitty noise as they flew overhead.", category: Category.ANIMALS },
  { id: 14, word: "Cluck", meaning: "The sound made by a hen.", example: "The hen clucked as she laid an egg.", category: Category.ANIMALS },
  { id: 15, word: "Cock-a-doodle-doo", meaning: "The crowing sound made by a rooster.", example: "The rooster's cock-a-doodle-doo woke up the farm.", category: Category.ANIMALS },
  { id: 16, word: "Coo", meaning: "The soft, murmuring sound made by doves or pigeons.", example: "The doves cooed in the tree.", category: Category.ANIMALS },
  { id: 17, word: "Croak", meaning: "The harsh, guttural sound made by a frog.", example: "The frog croaked in the pond.", category: Category.ANIMALS },
  { id: 18, word: "Crow", meaning: "The harsh cry of a rooster or a crow.", example: "The rooster crowed at the break of dawn.", category: Category.ANIMALS },
  { id: 19, word: "Cuckoo", meaning: "The call of the cuckoo bird.", example: "The cuckoo's call echoed through the forest.", category: Category.ANIMALS },
  { id: 20, word: "Flutter", meaning: "The rapid, irregular motion of wings or something similar.", example: "The butterflies fluttered around the flowers.", category: Category.ANIMALS },
  { id: 21, word: "Gaggle", meaning: "The cackling sound made by geese.", example: "The gaggle of geese flew overhead.", category: Category.ANIMALS },
  { id: 22, word: "Gallop", meaning: "The fast, rhythmic sound of a horse's hooves.", example: "The horse galloped across the field.", category: Category.ANIMALS },
  { id: 23, word: "Gibber", meaning: "To speak rapidly and incoherently.", example: "The madman gibbered nonsense.", category: Category.ANIMALS },
  { id: 24, word: "Growl", meaning: "A low, guttural sound made by an animal, often as a warning.", example: "The dog growled at the stranger.", category: Category.ANIMALS },
  { id: 25, word: "Grumble", meaning: "A low, rumbling sound, often expressing discontent.", example: "The thunder grumbled in the distance.", category: Category.ANIMALS },
  { id: 26, word: "Hee-haw", meaning: "The braying sound made by a donkey.", example: "The donkey let out a loud hee-haw.", category: Category.ANIMALS },
  { id: 27, word: "Hiss", meaning: "A sharp, sibilant sound, often made in anger or disapproval.", example: "The snake hissed warningly.", category: Category.ANIMALS },
  { id: 28, word: "Honk", meaning: "The sound made by a car horn.", example: "The taxi driver honked impatiently.", category: Category.ANIMALS },
  { id: 29, word: "Hoo", meaning: "The sound made by an owl.", example: "The owl hooted in the night.", category: Category.ANIMALS },
  { id: 30, word: "Hoot", meaning: "The deep sound made by an owl.", example: "The owl hooted loudly in the tree.", category: Category.ANIMALS },
  { id: 31, word: "Howl", meaning: "The long, mournful cry of a wolf or dog.", example: "The wolves howled at the moon.", category: Category.ANIMALS },
  { id: 32, word: "Jabber", meaning: "To talk rapidly and unintelligibly.", example: "The children jabbered excitedly about their day.", category: Category.ANIMALS },
  { id: 33, word: "Lap", meaning: "The sound of water gently washing against something.", example: "The waves lapped at the shore.", category: Category.ANIMALS },
  { id: 34, word: "Meow", meaning: "The sound made by a cat.", example: "The cat meowed for attention.", category: Category.ANIMALS },
  { id: 35, word: "Mew", meaning: "The sound made by a kitten.", example: "The kitten mewed softly.", category: Category.ANIMALS },
  { id: 36, word: "Moo", meaning: "The sound made by a cow.", example: "The cow mooed in the field.", category: Category.ANIMALS },
  { id: 37, word: "Neigh", meaning: "The sound made by a horse.", example: "The horse neighed as it saw its rider approach.", category: Category.ANIMALS },
  { id: 38, word: "Nicker", meaning: "The low, soft sound made by a horse.", example: "The horse nickered eagerly for its feed.", category: Category.ANIMALS },
  { id: 39, word: "Oink", meaning: "The sound made by a pig.", example: "The pig oinked happily in its pen.", category: Category.ANIMALS },
  { id: 40, word: "Peep", meaning: "A faint, high-pitched sound, like that of a chick.", example: "The baby bird peeped for its mother.", category: Category.ANIMALS },
  { id: 41, word: "Pip", meaning: "A short, high-pitched sound.", example: "The kettle piped as it boiled.", category: Category.ANIMALS },
  { id: 42, word: "Purr", meaning: "The sound made by a contented cat.", example: "The cat purred as it was stroked.", category: Category.ANIMALS },
  { id: 43, word: "Quack", meaning: "The sound made by a duck.", example: "The duck quacked loudly in the pond.", category: Category.ANIMALS },
  { id: 44, word: "Ribbit", meaning: "The sound made by a frog.", example: "The frog ribbited near the pond.", category: Category.ANIMALS },
  { id: 45, word: "Roar", meaning: "A loud, deep sound, like that of a lion or a strong wind.", example: "The lion let out a deafening roar.", category: Category.ANIMALS },
  { id: 46, word: "Scrabble", meaning: "A scratching or scraping sound.", example: "The mouse made a scrabble as it tried to escape.", category: Category.ANIMALS },
  { id: 47, word: "Screech", meaning: "A loud, high-pitched sound.", example: "The tires screeched as the car came to a sudden stop.", category: Category.ANIMALS },
  { id: 48, word: "Snarl", meaning: "A growling or vicious-sounding utterance.", example: "The dog gave a warning snarl.", category: Category.ANIMALS },
  { id: 49, word: "Squawk", meaning: "A harsh, loud cry, like that of a bird.", example: "The parrot squawked loudly in its cage.", category: Category.ANIMALS },
  { id: 50, word: "Squeak", meaning: "A short, high-pitched sound, like that of a mouse.", example: "The door squeaked on its hinges.", category: Category.ANIMALS },
  { id: 51, word: "Squeal", meaning: "A loud, high-pitched cry, often of excitement or fear.", example: "The children squealed with delight on the roller coaster.", category: Category.ANIMALS },
  { id: 52, word: "Tweet", meaning: "The sound made by a bird.", example: "The bird tweeted merrily in the tree.", category: Category.ANIMALS },
  { id: 53, word: "Twitter", meaning: "The rapid, light chirping sound made by birds.", example: "The sparrows twittered in the bushes.", category: Category.ANIMALS },
  { id: 54, word: "Warble", meaning: "A melodious singing sound.", example: "The bird warbled a beautiful tune.", category: Category.ANIMALS },
  { id: 55, word: "Whinny", meaning: "The sound made by a horse, especially when expressing excitement or greeting.", example: "The horse whinnied as its owner approached.", category: Category.ANIMALS },
  { id: 56, word: "Woof", meaning: "The sound made by a dog.", example: "The dog let out a loud woof.", category: Category.ANIMALS },
  { id: 57, word: "Yap", meaning: "A sharp, high-pitched bark.", example: "The small dog yapped at the passersby.", category: Category.ANIMALS },
  { id: 58, word: "Yelp", meaning: "A short, sharp cry, often of pain or alarm.", example: "The dog yelped when it was stepped on.", category: Category.ANIMALS },
  { id: 59, word: "Yip", meaning: "A short, sharp bark or cry.", example: "The puppy let out a yip of excitement.", category: Category.ANIMALS },

  // Collision or Explosive Sounds
  { id: 60, word: "Bam", meaning: "A loud, sudden impact or explosion.", example: "The door slammed shut with a bam.", category: Category.COLLISION },
  { id: 61, word: "Bang", meaning: "A loud, explosive sound.", example: "The fireworks went off with a bang.", category: Category.COLLISION },
  { id: 62, word: "Bash", meaning: "A heavy blow or impact.", example: "He gave the door a good bash with his shoulder.", category: Category.COLLISION },
  { id: 63, word: "Blast", meaning: "A loud, destructive explosion.", example: "The bomb went off with a blast.", category: Category.COLLISION },
  { id: 64, word: "Boink", meaning: "A light, bouncing impact.", example: "The ball boinked off the wall.", category: Category.COLLISION },
  { id: 65, word: "Bonk", meaning: "A dull, heavy impact.", example: "He bonked his head on the low ceiling.", category: Category.COLLISION },
  { id: 66, word: "Boom", meaning: "A deep, resonant sound, like that of an explosion.", example: "The fireworks boomed in the night sky.", category: Category.COLLISION },
  { id: 67, word: "Boop", meaning: "A light, playful tap or touch.", example: "She gave the kitten's nose a gentle boop.", category: Category.COLLISION },
  { id: 68, word: "Bop", meaning: "A quick, sharp blow.", example: "He bopped his brother on the head playfully.", category: Category.COLLISION },
  { id: 69, word: "Bump", meaning: "A light collision or impact.", example: "The car hit a bump in the road.", category: Category.COLLISION },
  { id: 70, word: "Burst", meaning: "A sudden, violent release of energy.", example: "The balloon burst with a loud pop.", category: Category.COLLISION },
  { id: 71, word: "Clack", meaning: "A sharp, clicking sound.", example: "The train wheels clacked on the tracks.", category: Category.COLLISION },
  { id: 72, word: "Clamor", meaning: "A loud, confused noise.", example: "The children's clamor filled the playground.", category: Category.COLLISION },
  { id: 73, word: "Clangor", meaning: "A loud, resonant banging or clanging sound.", example: "The clangor of the church bells echoed through town.", category: Category.COLLISION },
  { id: 74, word: "Clank", meaning: "A sharp, metallic sound.", example: "The chains clanked as the ghost walked.", category: Category.COLLISION },
  { id: 75, word: "Clash", meaning: "A loud, harsh noise of collision.", example: "The clash of cymbals signaled the end of the show.", category: Category.COLLISION },
  { id: 76, word: "Clatter", meaning: "A rapid series of noisy sounds.", example: "The dishes clattered as they fell to the floor.", category: Category.COLLISION },
  { id: 77, word: "Click", meaning: "A sharp, clicking sound.", example: "She heard the click of the lock as the door closed.", category: Category.COLLISION },
  { id: 78, word: "Clickety-clack", meaning: "The rhythmic sound of wheels on tracks.", example: "The train clickety-clacked along the rails.", category: Category.COLLISION },
  { id: 79, word: "Clink", meaning: "A light, metallic sound.", example: "The coins clinked as they fell into the jar.", category: Category.COLLISION },
  { id: 80, word: "Crash", meaning: "A loud, violent collision or impact.", example: "The waves crashed against the rocks.", category: Category.COLLISION },
  { id: 81, word: "Crush", meaning: "To violently compress or break something.", example: "The car was crushed in the accident.", category: Category.COLLISION },
  { id: 82, word: "Explode", meaning: "To burst violently, often with a loud noise.", example: "The firework exploded in a shower of colors.", category: Category.COLLISION },
  { id: 83, word: "Kaboom", meaning: "An onomatopoeic representation of a loud explosion.", example: "The bomb went off with a kaboom.", category: Category.COLLISION },
  { id: 84, word: "Kapow", meaning: "An onomatopoeic representation of a loud impact or explosion.", example: "The superhero's punch landed with a kapow.", category: Category.COLLISION },
  { id: 85, word: "Klunk", meaning: "A dull, heavy sound.", example: "The box fell to the ground with a klunk.", category: Category.COLLISION },
  { id: 86, word: "Knock", meaning: "A sharp rap or blow, often on a door.", example: "There was a knock at the door.", category: Category.COLLISION },
  { id: 87, word: "Pop", meaning: "A short, sharp, explosive sound.", example: "The balloon popped suddenly.", category: Category.COLLISION },
  { id: 88, word: "Pow", meaning: "An onomatopoeic representation of a punch or impact.", example: "Batman delivered a pow to the villain's jaw.", category: Category.COLLISION },
  { id: 89, word: "Punch", meaning: "A sharp blow with the fist.", example: "He punched the wall in frustration.", category: Category.COLLISION },
  { id: 90, word: "Shatter", meaning: "To break into many pieces with a loud noise.", example: "The glass shattered on the floor.", category: Category.COLLISION },
  { id: 91, word: "Slam", meaning: "To close forcefully and loudly.", example: "She slammed the door in anger.", category: Category.COLLISION },
  { id: 92, word: "Smack", meaning: "A sharp blow or slap.", example: "He gave the table a smack with his hand.", category: Category.COLLISION },
  { id: 93, word: "Snap", meaning: "To make a sharp, cracking sound.", example: "The twig snapped under his foot.", category: Category.COLLISION },
  { id: 94, word: "Sock", meaning: "A hard blow or punch.", example: "He gave the bully a sock in the jaw.", category: Category.COLLISION },
  { id: 95, word: "Spank", meaning: "To slap on the buttocks as a punishment.", example: "The child was spanked for misbehaving.", category: Category.COLLISION },
  { id: 96, word: "Spark", meaning: "A small fiery particle thrown off from a fire or flame.", example: "The spark ignited the dry leaves.", category: Category.COLLISION },
  { id: 97, word: "Thud", meaning: "A dull, heavy sound, like that of a heavy object falling.", example: "The book fell to the floor with a thud.", category: Category.COLLISION },
  { id: 98, word: "Thump", meaning: "A heavy blow or impact.", example: "He felt a thump on his back.", category: Category.COLLISION },
  { id: 99, word: "Thwack", meaning: "A sharp blow or smack.", example: "The tennis ball thwacked against the wall.", category: Category.COLLISION },
  { id: 100, word: "Whale", meaning: "To strike or hit hard.", example: "He whaled on the punching bag for exercise.", category: Category.COLLISION },
  { id: 101, word: "Wham", meaning: "A heavy blow or impact.", example: "The door slammed shut with a wham.", category: Category.COLLISION },
  { id: 102, word: "Whomp", meaning: "A heavy, thudding impact.", example: "The sack of flour whomped onto the floor.", category: Category.COLLISION },
  { id: 103, word: "Whump", meaning: "A dull, heavy impact.", example: "The tree branch whumped against the ground.", category: Category.COLLISION },

  // Musical Sounds
  { id: 104, word: "Beep", meaning: "A short, high-pitched sound emitted by electronic devices.", example: "The alarm clock beeped loudly, waking him up.", category: Category.MUSICAL },
  { id: 105, word: "Blare", meaning: "To make a loud, harsh sound.", example: "The trumpet blared as the parade passed by.", category: Category.MUSICAL },
  { id: 106, word: "Bleep", meaning: "A short, high-pitched sound, especially as emitted by an electronic device.", example: "The censor bleeped out the swear word on TV.", category: Category.MUSICAL },
  { id: 107, word: "Bloop", meaning: "A short, low-pitched sound, like that of a bubble popping.", example: "The fish made a bloop as it jumped out of the water.", category: Category.MUSICAL },
  { id: 108, word: "Bong", meaning: "A deep, resonant sound, like that of a bell.", example: "The clock bonged midnight.", category: Category.MUSICAL },
  { id: 109, word: "Buzz", meaning: "A low, continuous humming or vibrating sound.", example: "The bee buzzed around the flower.", category: Category.MUSICAL },
  { id: 110, word: "Chime", meaning: "A melodious ringing sound, typically produced by bells.", example: "The church bells chimed to mark the hour.", category: Category.MUSICAL },
  { id: 111, word: "Clang", meaning: "A loud, resonant metallic sound.", example: "The hammer hit the metal with a clang.", category: Category.MUSICAL },
  { id: 112, word: "Ding", meaning: "A short, ringing sound.", example: "The microwave dinged to indicate that the food was ready.", category: Category.MUSICAL },
  { id: 113, word: "Ding-a-ling", meaning: "A jocular term for a bell or a person who is eccentric or slightly crazy.", example: "She's a bit of a xding-a-ling, always forgetting where she put her keys.", category: Category.MUSICAL },
  { id: 114, word: "Ding-dong", meaning: "The sound of a bell ringing.", example: "The doorbell went ding-dong, announcing the arrival of the guests.", category: Category.MUSICAL },
  { id: 115, word: "Dong", meaning: "A deep, resonant sound, like that of a bell.", example: "The grandfather clock struck twelve with a deep dong.", category: Category.MUSICAL },
  { id: 116, word: "Drum", meaning: "To play a drum or drums.", example: "He drummed his fingers on the table impatiently.", category: Category.MUSICAL },
  { id: 117, word: "Gong", meaning: "A large metal disk that produces a deep, resonant sound when struck.", example: "The gong sounded, signaling the start of the ceremony.", category: Category.MUSICAL },
  { id: 118, word: "Jingle", meaning: "A light, ringing sound, like that of coins or small bells.", example: "The keys jingled as he walked.", category: Category.MUSICAL },
  { id: 119, word: "Ka-ching", meaning: "An onomatopoeic representation of a cash register or money being counted.", example: "Every time a sale was made, the cash register went ka-ching.", category: Category.MUSICAL },
  { id: 120, word: "Knell", meaning: "The sound of a bell, especially when rung solemnly for a death or funeral.", example: "The knell of the church bell echoed through the village.", category: Category.MUSICAL },
  { id: 121, word: "Oompah", meaning: "A rhythmic sound, often associated with tuba and other brass instruments in a band.", example: "The oompah band played at the Oktoberfest celebrations.", category: Category.MUSICAL },
  { id: 122, word: "Pick", meaning: "To pluck or play a stringed instrument, producing a sharp, clear sound.", example: "He picked the guitar strings softly.", category: Category.MUSICAL },
  { id: 123, word: "Ping", meaning: "A short, high-pitched ringing sound.", example: "The microwave pinged to indicate that the food was ready.", category: Category.MUSICAL },
  { id: 124, word: "Plink", meaning: "A short, sharp, metallic sound.", example: "The raindrops plinked against the windowpane.", category: Category.MUSICAL },
  { id: 125, word: "Pluck", meaning: "To pull or pick at (a string or instrument) to produce a sound.", example: "She plucked the harp strings gently.", category: Category.MUSICAL },
  { id: 126, word: "Plunk", meaning: "To play a stringed instrument or to drop something with a dull, metallic sound.", example: "He plunked the guitar string, producing a twangy sound.", category: Category.MUSICAL },
  { id: 127, word: "Pong", meaning: "A short, resonant sound, like that of a bell or a drum.", example: "The bell ponged softly in the distance.", category: Category.MUSICAL },
  { id: 128, word: "Rat-a-tat", meaning: "A rapid succession of sharp, tapping sounds.", example: "The machine gun went rat-a-tat-tat.", category: Category.MUSICAL },
  { id: 129, word: "Ring", meaning: "To produce a clear, resonant sound, like that of a bell.", example: "The telephone rang loudly in the empty house.", category: Category.MUSICAL },
  { id: 130, word: "Throb", meaning: "To beat or pulsate with a strong, regular rhythm.", example: "His head throbbed with pain.", category: Category.MUSICAL },
  { id: 131, word: "Ting", meaning: "A light, metallic ringing sound.", example: "The spoon tinged against the glass.", category: Category.MUSICAL },
  { id: 132, word: "Tinkle", meaning: "To make a light, ringing sound.", example: "The wind chimes tinkled in the breeze.", category: Category.MUSICAL },
  { id: 133, word: "Tintinnabulation", meaning: "The ringing or sound of bells.", example: "The tintinnabulation of the church bells could be heard throughout the village.", category: Category.MUSICAL },
  { id: 134, word: "Toot", meaning: "To emit a short, sharp sound, like that of a horn.", example: "The car tooted its horn as it drove away.", category: Category.MUSICAL },
  { id: 135, word: "Trill", meaning: "To produce a quavering or warbling sound.", example: "The bird trilled its song in the morning.", category: Category.MUSICAL },
  { id: 136, word: "Twang", meaning: "To produce a sharp, vibrating sound, like that of a plucked string.", example: "The banjo twanged as he played.", category: Category.MUSICAL },
  { id: 137, word: "Zing", meaning: "To move swiftly with a high-pitched buzzing or whizzing sound.", example: "The arrow zinged past his ear.", category: Category.MUSICAL },

  // Movement of Water, Air, or Objects
  { id: 138, word: "Blaze", meaning: "To burn brightly and intensely.", example: "The fire blazed in the fireplace.", category: Category.WATER_AIR_OBJECTS },
  { id: 139, word: "Blimp", meaning: "A type of non-rigid airship.", example: "The blimp floated gracefully in the sky.", category: Category.WATER_AIR_OBJECTS },
  { id: 140, word: "Bling", meaning: "Expensive, ostentatious clothing and jewellery.", example: "She was covered in bling from head to toe.", category: Category.WATER_AIR_OBJECTS },
  { id: 141, word: "Blip", meaning: "A small, sudden change or interruption.", example: "The blip on the radar indicated an approaching storm.", category: Category.WATER_AIR_OBJECTS },
  { id: 142, word: "Blow", meaning: "To produce an air current.", example: "The wind blew through the trees.", category: Category.WATER_AIR_OBJECTS },
  { id: 143, word: "Boing", meaning: "A springing or bouncing sound.", example: "The rubber ball went boing when it hit the floor.", category: Category.WATER_AIR_OBJECTS },
  { id: 144, word: "Bounce", meaning: "To spring back after hitting a surface.", example: "The ball bounced off the wall.", category: Category.WATER_AIR_OBJECTS },
  { id: 145, word: "Brouhaha", meaning: "An uproar or hubbub.", example: "There was a brouhaha when the celebrity arrived.", category: Category.WATER_AIR_OBJECTS },
  { id: 146, word: "Bumble", meaning: "To move or act clumsily or ineptly.", example: "He bumbled his way through the dance.", category: Category.WATER_AIR_OBJECTS },
  { id: 147, word: "Burble", meaning: "To make a continuous murmuring noise.", example: "The stream burbled as it flowed over the rocks.", category: Category.WATER_AIR_OBJECTS },
  { id: 148, word: "Cha-cha", meaning: "A dance to a Latin American rhythm.", example: "They danced the cha-cha at the party.", category: Category.WATER_AIR_OBJECTS },
  { id: 149, word: "Cha-ching", meaning: "An onomatopoeic representation of a cash register or money being counted.", example: "The cash register went cha-ching as he made a sale.", category: Category.WATER_AIR_OBJECTS },
  { id: 150, word: "Choo-choo", meaning: "An onomatopoeic representation of the sound of a train.", example: "The children played with their toy train, making it go choo-choo.", category: Category.WATER_AIR_OBJECTS },
  { id: 151, word: "Chug", meaning: "To make a dull, explosive sound, like that of a steam engine.", example: "The old car chugged up the hill.", category: Category.WATER_AIR_OBJECTS },
  { id: 152, word: "Clonk", meaning: "To make a dull, heavy, metallic sound.", example: "The hammer clonked against the metal.", category: Category.WATER_AIR_OBJECTS },
  { id: 153, word: "Clunk", meaning: "To make a heavy, dull sound, like that of something being dropped.", example: "The box clunked to the ground.", category: Category.WATER_AIR_OBJECTS },
  { id: 154, word: "Crack", meaning: "To make a sharp, sudden, explosive sound.", example: "The whip cracked in the air.", category: Category.WATER_AIR_OBJECTS },
  { id: 155, word: "Crackle", meaning: "To make a series of slight, sharp snapping noises.", example: "The fire crackled as it burned.", category: Category.WATER_AIR_OBJECTS },
  { id: 156, word: "Creak", meaning: "To make a harsh, high-pitched sound when pressure or weight is applied.", example: "The door creaked as it opened slowly.", category: Category.WATER_AIR_OBJECTS },
  { id: 157, word: "Crinkle", meaning: "To make a soft, crackling sound.", example: "The paper crinkled as she folded it.", category: Category.WATER_AIR_OBJECTS },
  { id: 158, word: "Dab", meaning: "To apply something with light, quick strokes.", example: "She dabbed perfume behind her ears.", category: Category.WATER_AIR_OBJECTS },
  { id: 159, word: "Dribble", meaning: "To flow or let flow in small drops or a thin stream.", example: "The faucet dripped, dribbling water into the sink.", category: Category.WATER_AIR_OBJECTS },
  { id: 160, word: "Drip", meaning: "To fall or let fall in drops.", example: "The rain dripped from the leaves.", category: Category.WATER_AIR_OBJECTS },
  { id: 161, word: "Drizzle", meaning: "To rain lightly and steadily.", example: "The weather forecast predicted a drizzle in the afternoon.", category: Category.WATER_AIR_OBJECTS },
  { id: 162, word: "Fizz", meaning: "To make a hissing or bubbling sound.", example: "The soda fizzed as she poured it into the glass.", category: Category.WATER_AIR_OBJECTS },
  { id: 163, word: "Fizzle", meaning: "To make a hissing or sputtering sound.", example: "The fireworks fizzled in the rain.", category: Category.WATER_AIR_OBJECTS },
  { id: 164, word: "Flap", meaning: "To move up and down or back and forth with a slapping sound.", example: "The bird flapped its wings and flew away.", category: Category.WATER_AIR_OBJECTS },
  { id: 165, word: "Flash", meaning: "To shine brightly and suddenly.", example: "The lightning flashed across the sky.", category: Category.WATER_AIR_OBJECTS },
  { id: 166, word: "Flick", meaning: "To move or hit something with a quick, light stroke.", example: "She flicked the switch and the light turned on.", category: Category.WATER_AIR_OBJECTS },
  { id: 167, word: "Fling", meaning: "To throw or hurl forcefully.", example: "He flung the ball across the field.", category: Category.WATER_AIR_OBJECTS },
  { id: 168, word: "Flip", meaning: "To turn over or cause to turn over with a sudden quick movement.", example: "She flipped the pancake in the air.", category: Category.WATER_AIR_OBJECTS },
  { id: 169, word: "Flip Flop", meaning: "To make a light, slapping sound, like sandals hitting the ground.", example: "The flip flops flopped as she walked.", category: Category.WATER_AIR_OBJECTS },
  { id: 170, word: "Flog", meaning: "To beat or whip as punishment.", example: "The criminal was flogged for his crimes.", category: Category.WATER_AIR_OBJECTS },
  { id: 171, word: "Flop", meaning: "To fall, collapse, or fail suddenly and completely.", example: "The company's stock price flopped after the scandal.", category: Category.WATER_AIR_OBJECTS },
  { id: 172, word: "Flush", meaning: "To flow or gush suddenly and rapidly.", example: "The toilet flushed with a loud whoosh.", category: Category.WATER_AIR_OBJECTS },
  { id: 173, word: "Gloop", meaning: "A thick, sticky substance.", example: "The mud was a gloopy mess.", category: Category.WATER_AIR_OBJECTS },
  { id: 174, word: "Glug", meaning: "To pour or drink with a gurgling sound.", example: "He glugged down the water after the long run.", category: Category.WATER_AIR_OBJECTS },
  { id: 175, word: "Grind", meaning: "To make a scraping or grinding sound.", example: "The gears ground as he shifted into reverse.", category: Category.WATER_AIR_OBJECTS },
  { id: 176, word: "Gurgle", meaning: "To make a bubbling or gurgling sound.", example: "The stream gurgled as it flowed over the rocks.", category: Category.WATER_AIR_OBJECTS },
  { id: 177, word: "Gush", meaning: "To flow out rapidly and in large quantities.", example: "The water gushed from the broken pipe.", category: Category.WATER_AIR_OBJECTS },
  { id: 178, word: "Jab", meaning: "To poke or thrust abruptly.", example: "He jabbed his finger at the map.", category: Category.WATER_AIR_OBJECTS },
  { id: 179, word: "Jangle", meaning: "To make a harsh, metallic ringing sound.", example: "The keys jangled as he walked.", category: Category.WATER_AIR_OBJECTS },
  { id: 180, word: "Jar", meaning: "To shake or jolt abruptly.", example: "The rough road jarred the car.", category: Category.WATER_AIR_OBJECTS },
  { id: 181, word: "Kerplink", meaning: "A light, metallic sound.", example: "The coin fell into the jar with a kerplink.", category: Category.WATER_AIR_OBJECTS },
  { id: 182, word: "Kerplunk", meaning: "A heavy object falling into water.", example: "The rock fell into the pond with a kerplunk.", category: Category.WATER_AIR_OBJECTS },
  { id: 183, word: "Mash", meaning: "To crush or squeeze something into a soft mass.", example: "She mashed the potatoes with butter.", category: Category.WATER_AIR_OBJECTS },
  { id: 184, word: "Nuzzle", meaning: "To rub gently against someone with the nose or mouth.", example: "The puppy nuzzle against her leg.", category: Category.WATER_AIR_OBJECTS },
  { id: 185, word: "Oomph", meaning: "A quality of excitement, vigor, or charisma.", example: "She performed with oomph on stage.", category: Category.WATER_AIR_OBJECTS },
  { id: 186, word: "Ooze", meaning: "To flow or leak out slowly.", example: "The mud oozed between his toes.", category: Category.WATER_AIR_OBJECTS },
  { id: 187, word: "Paddle", meaning: "To move through water using hands or feet.", example: "They paddled the canoe down the river.", category: Category.WATER_AIR_OBJECTS },
  { id: 188, word: "Patter", meaning: "To make a rapid succession of light, tapping sounds.", example: "The rain pattered against the window.", category: Category.WATER_AIR_OBJECTS },
  { id: 189, word: "Pitter", meaning: "To make a series of light, quick sounds.", example: "The hail pittered against the roof.", category: Category.WATER_AIR_OBJECTS },
  { id: 190, word: "Plash", meaning: "To make a gentle splash or splashing sound.", example: "The water plashed against the shore.", category: Category.WATER_AIR_OBJECTS },
  { id: 191, word: "Plop", meaning: "To fall or drop into water.", example: "The stone plopped into the pond.", category: Category.WATER_AIR_OBJECTS },
  { id: 192, word: "Puff", meaning: "To emit a sudden burst of air or smoke.", example: "She puffed on her cigarette.", category: Category.WATER_AIR_OBJECTS },
  { id: 193, word: "Pump", meaning: "To move with a pumping action.", example: "He pumped the handle to fill the bucket.", category: Category.WATER_AIR_OBJECTS },
  { id: 194, word: "Quiver", meaning: "To tremble or shake with a slight rapid motion.", example: "Her lip quivered as she tried not to cry.", category: Category.WATER_AIR_OBJECTS },
  { id: 195, word: "Racket", meaning: "A loud, disturbing noise.", example: "The children made a racket in the playground.", category: Category.WATER_AIR_OBJECTS },
  { id: 196, word: "Rap", meaning: "To strike sharply with a light blow.", example: "He rapped on the door with his knuckles.", category: Category.WATER_AIR_OBJECTS },
  { id: 197, word: "Rattle", meaning: "To make a rapid succession of short sounds.", example: "The windows rattled in the wind.", category: Category.WATER_AIR_OBJECTS },
  { id: 198, word: "Rev", meaning: "To increase the speed of an engine.", example: "He revved the motorcycle before taking off.", category: Category.WATER_AIR_OBJECTS },
  { id: 199, word: "Rip", meaning: "To tear or pull something apart forcefully.", example: "She ripped the paper in half.", category: Category.WATER_AIR_OBJECTS },
  { id: 200, word: "Rumble", meaning: "To make a continuous, deep, resonant sound.", example: "The thunder rumbled in the distance.", category: Category.WATER_AIR_OBJECTS },
  { id: 201, word: "Rustle", meaning: "To make a soft, muffled crackling sound.", example: "The leaves rustled in the breeze.", category: Category.WATER_AIR_OBJECTS },
  { id: 202, word: "Scour", meaning: "To clean or polish something thoroughly.", example: "She scoured the pots until they sparkled.", category: Category.WATER_AIR_OBJECTS },
  { id: 203, word: "Scramble", meaning: "To move quickly or awkwardly using hands and feet.", example: "The hikers scrambled up the slope.", category: Category.WATER_AIR_OBJECTS },
  { id: 204, word: "Scrape", meaning: "To rub against a rough surface, making a harsh noise.", example: "The chair scraped against the floor.", category: Category.WATER_AIR_OBJECTS },
  { id: 205, word: "Scrub", meaning: "To clean something by rubbing it hard.", example: "She scrubbed the floor on her hands and knees.", category: Category.WATER_AIR_OBJECTS },
  { id: 206, word: "Scrunch", meaning: "To crush something into a compact mass.", example: "He scrunched up the paper.", category: Category.WATER_AIR_OBJECTS },
  { id: 207, word: "Scuffle", meaning: "To struggle or fight in a rough manner.", example: "The two men scuffled in the street.", category: Category.WATER_AIR_OBJECTS },
  { id: 208, word: "Shiver", meaning: "To tremble involuntarily from cold or fear.", example: "She shivered in the cold wind.", category: Category.WATER_AIR_OBJECTS },
  { id: 209, word: "Shred", meaning: "To tear something into narrow pieces.", example: "He shredded the document.", category: Category.WATER_AIR_OBJECTS },
  { id: 210, word: "Shudder", meaning: "To tremble involuntarily from fear or disgust.", example: "She shuddered at the thought of spiders.", category: Category.WATER_AIR_OBJECTS },
  { id: 211, word: "Shuffle", meaning: "To walk by dragging one's feet.", example: "He shuffled his feet as he walked.", category: Category.WATER_AIR_OBJECTS },
  { id: 212, word: "Sizzle", meaning: "To make a hissing or bubbling sound.", example: "The steak sizzled in the pan.", category: Category.WATER_AIR_OBJECTS },
  { id: 213, word: "Skip", meaning: "To move along lightly with a hop or bounce.", example: "The children skipped down the path.", category: Category.WATER_AIR_OBJECTS },
  { id: 214, word: "Slash", meaning: "To cut with a sweeping stroke violently.", example: "He slashed the painting with a knife.", category: Category.WATER_AIR_OBJECTS },
  { id: 215, word: "Slick", meaning: "To make something smooth and shiny.", example: "She slicked back her hair with gel.", category: Category.WATER_AIR_OBJECTS },
  { id: 216, word: "Slither", meaning: "To move smoothly with a twisting motion.", example: "The snake slithered through the grass.", category: Category.WATER_AIR_OBJECTS },
  { id: 217, word: "Slop", meaning: "To spill liquid carelessly.", example: "He slopped coffee all over the table.", category: Category.WATER_AIR_OBJECTS },
  { id: 218, word: "Slosh", meaning: "To move with a splashing sound.", example: "The water sloshed around in the bucket.", category: Category.WATER_AIR_OBJECTS },
  { id: 219, word: "Slurp", meaning: "To eat or drink something noisily.", example: "He slurped his soup from the bowl.", category: Category.WATER_AIR_OBJECTS },
  { id: 220, word: "Slush", meaning: "A mixture of snow and water.", example: "The streets were covered in slush.", category: Category.WATER_AIR_OBJECTS },
  { id: 221, word: "Snip", meaning: "To cut with scissors in a quick stroke.", example: "She snipped off a piece of thread.", category: Category.WATER_AIR_OBJECTS },
  { id: 222, word: "Sparkle", meaning: "To shine brightly with flashes of light.", example: "The diamonds sparkled in the sunlight.", category: Category.WATER_AIR_OBJECTS },
  { id: 223, word: "Splash", meaning: "To cause liquid to scatter in drops.", example: "He splashed water on his face.", category: Category.WATER_AIR_OBJECTS },
  { id: 224, word: "Splat", meaning: "Sound of something wet hitting a surface.", example: "The paintball splat against the wall.", category: Category.WATER_AIR_OBJECTS },
  { id: 225, word: "Splatter", meaning: "To cover something with drops of liquid.", example: "The rain splattered against the window.", category: Category.WATER_AIR_OBJECTS },
  { id: 226, word: "Sploosh", meaning: "Representation of a splashing sound.", example: "He jumped into the pool with a sploosh.", category: Category.WATER_AIR_OBJECTS },
  { id: 227, word: "Splosh", meaning: "To make a splashing sound.", example: "The children sploshed through the puddles.", category: Category.WATER_AIR_OBJECTS },
  { id: 228, word: "Splutter", meaning: "To speak rapidly and incoherently.", example: "He spluttered his apologies.", category: Category.WATER_AIR_OBJECTS },
  { id: 229, word: "Sprinkle", meaning: "To scatter in drops or particles.", example: "She sprinkled cinnamon on the cake.", category: Category.WATER_AIR_OBJECTS },
  { id: 230, word: "Squelch", meaning: "To make a sucking sound walking through mud.", example: "His boots squelched in the wet grass.", category: Category.WATER_AIR_OBJECTS },
  { id: 231, word: "Squirt", meaning: "To eject liquid in a thin fast stream.", example: "He squirted ketchup onto his burger.", category: Category.WATER_AIR_OBJECTS },
  { id: 232, word: "Squish", meaning: "To make a soft, wet, squelching sound.", example: "The mud squished under his feet.", category: Category.WATER_AIR_OBJECTS },
  { id: 233, word: "Strum", meaning: "To play a stringed instrument with sweeping fingers.", example: "He strummed the guitar softly.", category: Category.WATER_AIR_OBJECTS },
  { id: 234, word: "Suck", meaning: "To draw into the mouth by contracting muscles.", example: "She sucked on a straw.", category: Category.WATER_AIR_OBJECTS },
  { id: 235, word: "Swarm", meaning: "To move in large numbers like insects.", example: "The bees swarmed around the hive.", category: Category.WATER_AIR_OBJECTS },
  { id: 236, word: "Swat", meaning: "To hit something with a sharp blow.", example: "She swatted at the mosquito.", category: Category.WATER_AIR_OBJECTS },
  { id: 237, word: "Swell", meaning: "To increase in size from pressure.", example: "The river swelled after heavy rain.", category: Category.WATER_AIR_OBJECTS },
  { id: 238, word: "Swish", meaning: "To move with a hissing or rushing sound.", example: "The wind swished through the trees.", category: Category.WATER_AIR_OBJECTS },
  { id: 239, word: "Swoop", meaning: "To descend rapidly and forcefully.", example: "The eagle swooped down from the sky.", category: Category.WATER_AIR_OBJECTS },
  { id: 240, word: "Swoosh", meaning: "To move with a rushing sound through air.", example: "The basketball swooshed through the net.", category: Category.WATER_AIR_OBJECTS },
  { id: 241, word: "Tear", meaning: "To pull apart or move very quickly.", example: "She tore the paper in half.", category: Category.WATER_AIR_OBJECTS },
  { id: 242, word: "Thrash", meaning: "To beat repeatedly and violently.", example: "He thrashed the water as he swam.", category: Category.WATER_AIR_OBJECTS },
  { id: 243, word: "Tick", meaning: "To make a light, sharp, clicking sound.", example: "The clock ticked away the minutes.", category: Category.WATER_AIR_OBJECTS },
  { id: 244, word: "Tick Tock", meaning: "Sound of a clock ticking.", example: "The old clock went tick tock.", category: Category.WATER_AIR_OBJECTS },
  { id: 245, word: "Tock", meaning: "Sound of a clock striking the hour.", example: "The clock went tock at midnight.", category: Category.WATER_AIR_OBJECTS },
  { id: 246, word: "Trickle", meaning: "To flow in drops or thin stream.", example: "Water trickled down the rock face.", category: Category.WATER_AIR_OBJECTS },
  { id: 247, word: "Trudge", meaning: "To walk slowly and with heavy steps.", example: "They trudged through the snow.", category: Category.WATER_AIR_OBJECTS },
  { id: 248, word: "Tug", meaning: "To pull something hard or suddenly.", example: "He tugged at the rope.", category: Category.WATER_AIR_OBJECTS },
  { id: 249, word: "Twinkle", meaning: "To shine with a flickering light.", example: "The stars twinkled in the night sky.", category: Category.WATER_AIR_OBJECTS },
  { id: 250, word: "Twist", meaning: "To turn or bend something.", example: "She twisted the cap off.", category: Category.WATER_AIR_OBJECTS },
  { id: 251, word: "Vroom", meaning: "Sound of a car engine revving.", example: "The motorcycle vroomed past us.", category: Category.WATER_AIR_OBJECTS },
  { id: 252, word: "Waft", meaning: "To pass easily or gently through the air.", example: "The smell of bread wafted from the bakery.", category: Category.WATER_AIR_OBJECTS },
  { id: 253, word: "Whip", meaning: "To move quickly and forcefully.", example: "The wind whipped through the trees.", category: Category.WATER_AIR_OBJECTS },
  { id: 254, word: "Whirl", meaning: "To move rapidly in a circle.", example: "The dancer whirled across the stage.", category: Category.WATER_AIR_OBJECTS },
  { id: 255, word: "Whirr", meaning: "To make a low, continuous, regular sound.", example: "The machine whirred as it printed.", category: Category.WATER_AIR_OBJECTS },
  { id: 256, word: "Whiz", meaning: "To move quickly with a whistling sound.", example: "The ball whizzed past the goalkeeper.", category: Category.WATER_AIR_OBJECTS },
  { id: 257, word: "Whoosh", meaning: "To move suddenly with a rushing sound.", example: "The rocket whooshed into the sky.", category: Category.WATER_AIR_OBJECTS },
  { id: 258, word: "Wobble", meaning: "To move unsteadily from side to side.", example: "The table wobbled on uneven legs.", category: Category.WATER_AIR_OBJECTS },
  { id: 259, word: "Woo", meaning: "To seek favor using flattery.", example: "The politician tried to woo voters.", category: Category.WATER_AIR_OBJECTS },
  { id: 260, word: "Zap", meaning: "To strike suddenly and with force.", example: "The superhero zapped the villain.", category: Category.WATER_AIR_OBJECTS },
  { id: 261, word: "Zoom", meaning: "To move quickly with a low humming sound.", example: "The car zoomed past us.", category: Category.WATER_AIR_OBJECTS },

  // Human Sounds
  { id: 262, word: "Babble", meaning: "To talk rapidly in a foolish way.", example: "The brook babbled softly.", category: Category.HUMAN },
  { id: 263, word: "Barf", meaning: "To vomit.", example: "She barfed after eating too much.", category: Category.HUMAN },
  { id: 264, word: "Bawl", meaning: "To cry out loudly.", example: "The baby bawled for attention.", category: Category.HUMAN },
  { id: 265, word: "Belch", meaning: "To expel gas noisily from the stomach.", example: "He belched loudly after the soda.", category: Category.HUMAN },
  { id: 266, word: "Bellow", meaning: "To emit a deep, loud roar.", example: "The lion bellowed in the distance.", category: Category.HUMAN },
  { id: 267, word: "Blab/Blabber", meaning: "To talk excessively or indiscreetly.", example: "She blabbed the secret.", category: Category.HUMAN },
  { id: 268, word: "Blub/Blubber", meaning: "To cry noisily and uncontrollably.", example: "He blubbered after the movie.", category: Category.HUMAN },
  { id: 269, word: "Blurt", meaning: "To say something suddenly without thinking.", example: "He blurted out the answer.", category: Category.HUMAN },
  { id: 270, word: "Boohoo", meaning: "To cry noisily.", example: "She boohooed over her dropped ice cream.", category: Category.HUMAN },
  { id: 271, word: "Burp", meaning: "To expel gas noisily; belch.", example: "The baby burped after feeding.", category: Category.HUMAN },
  { id: 272, word: "Bwahaha", meaning: "An evil laugh or expression of triumph.", example: "The villain laughed, 'Bwahaha!'", category: Category.HUMAN },
  { id: 273, word: "Chant", meaning: "To repeat a phrase continuously.", example: "The crowd chanted the team's name.", category: Category.HUMAN },
  { id: 274, word: "Chat", meaning: "To talk in a friendly, informal way.", example: "They chatted about their plans.", category: Category.HUMAN },
  { id: 275, word: "Chatter", meaning: "To talk rapidly about trivial matters.", example: "The birds chattered in the trees.", category: Category.HUMAN },
  { id: 276, word: "Chomp", meaning: "To bite or chew noisily.", example: "He chomped on an apple.", category: Category.HUMAN },
  { id: 277, word: "Chortle", meaning: "To chuckle gleefully.", example: "He chortled at the joke.", category: Category.HUMAN },
  { id: 278, word: "Clap", meaning: "To strike palms together.", example: "The audience clapped after the show.", category: Category.HUMAN },
  { id: 279, word: "Cough", meaning: "To expel air from lungs with sharp sound.", example: "He coughed to clear his throat.", category: Category.HUMAN },
  { id: 280, word: "Cringe", meaning: "To bend head in fear or apprehension.", example: "She cringed at public speaking.", category: Category.HUMAN },
  { id: 281, word: "Croup", meaning: "Coughing condition with barking sound.", example: "The child had a croupy cough.", category: Category.HUMAN },
  { id: 282, word: "Crunch", meaning: "To crush with a noisy crackling sound.", example: "He crunched on the crisp apple.", category: Category.HUMAN },
  { id: 283, word: "Cry", meaning: "To shed tears expressing pain or sorrow.", example: "She cried at the sad news.", category: Category.HUMAN },
  { id: 284, word: "Drone", meaning: "To make a continuous low humming sound.", example: "The drone of bees was in the garden.", category: Category.HUMAN },
  { id: 285, word: "Echo", meaning: "Repeated sound caused by reflection.", example: "Her voice echoed in the hallway.", category: Category.HUMAN },
  { id: 286, word: "Fart", meaning: "Expulsion of gas from the anus.", example: "He farted loudly and was embarrassed.", category: Category.HUMAN },
  { id: 287, word: "Foofaraw", meaning: "Excessive or flashy ornamentation.", example: "The ceremony was full of foofaraw.", category: Category.HUMAN },
  { id: 288, word: "Garble", meaning: "To reproduce sound in a distorted way.", example: "The bad connection garbled his words.", category: Category.HUMAN },
  { id: 289, word: "Gargle", meaning: "To rinse throat with liquid in motion.", example: "She gargled with saltwater.", category: Category.HUMAN },
  { id: 290, word: "Gasp", meaning: "To inhale suddenly from surprise.", example: "She gasped when she saw the price.", category: Category.HUMAN },
  { id: 291, word: "Giggle", meaning: "To laugh lightly in a silly way.", example: "The girls giggled at the joke.", category: Category.HUMAN },
  { id: 292, word: "Gnash", meaning: "To grind teeth together from rage.", example: "He gnashed his teeth in frustration.", category: Category.HUMAN },
  { id: 293, word: "Gnaw", meaning: "To bite or chew repeatedly.", example: "The dog gnawed on the bone.", category: Category.HUMAN },
  { id: 294, word: "Gobble", meaning: "To eat quickly and greedily.", example: "He gobbled down his food.", category: Category.HUMAN },
  { id: 295, word: "Groan", meaning: "Deep sound in response to pain.", example: "He groaned when he tried to stand.", category: Category.HUMAN },
  { id: 296, word: "Grump", meaning: "To complain in a surly manner.", example: "He grumped about the cold.", category: Category.HUMAN },
  { id: 297, word: "Grunt", meaning: "To make a short, low sound.", example: "The pig grunted in the mud.", category: Category.HUMAN },
  { id: 298, word: "Guffaw", meaning: "To laugh loudly and boisterously.", example: "He guffawed at the comedian.", category: Category.HUMAN },
  { id: 299, word: "Gulp", meaning: "To swallow quickly and audibly.", example: "He gulped down his drink.", category: Category.HUMAN },
  { id: 300, word: "Hack", meaning: "To cough roughly or harshly.", example: "He hacked after inhaling smoke.", category: Category.HUMAN },
  { id: 301, word: "Hiccup", meaning: "Sharp involuntary inhalation.", example: "She hiccuped after drinking too fast.", category: Category.HUMAN },
  { id: 302, word: "Holler", meaning: "To shout loudly or yell.", example: "He hollered for help.", category: Category.HUMAN },
  { id: 303, word: "Hoopla", meaning: "Excited commotion or publicity.", example: "The premiere was full of hoopla.", category: Category.HUMAN },
  { id: 304, word: "Huff", meaning: "To emit a breath in a noisy manner.", example: "She huffed in annoyance.", category: Category.HUMAN },
  { id: 305, word: "Hum", meaning: "To make a continuous low sound.", example: "The fridge hummed in the background.", category: Category.HUMAN },
  { id: 306, word: "Humph", meaning: "Exclamation of doubt or disdain.", example: "'Humph,' she said, unconvinced.", category: Category.HUMAN },
  { id: 307, word: "Hush", meaning: "To make or become silent.", example: "She hushed the children.", category: Category.HUMAN },
  { id: 308, word: "Lisp", meaning: "Pronounce 's' and 'z' as 'th'.", example: "The child lisped slightly.", category: Category.HUMAN },
  { id: 309, word: "Mewl", meaning: "To cry weakly or querulously.", example: "The kitten mewled for its mother.", category: Category.HUMAN },
  { id: 310, word: "Moan", meaning: "Long low sound expressing pain.", example: "He moaned in agony.", category: Category.HUMAN },
  { id: 311, word: "Mumble", meaning: "To speak in a low, unclear way.", example: "He mumbled his apology.", category: Category.HUMAN },
  { id: 312, word: "Munch", meaning: "To eat with steady audible biting.", example: "He munched on popcorn.", category: Category.HUMAN },
  { id: 313, word: "Murmur", meaning: "Say something in low, soft voice.", example: "The river murmured over rocks.", category: Category.HUMAN },
  { id: 314, word: "Mutter", meaning: "Speak quietly when complaining.", example: "He muttered under his breath.", category: Category.HUMAN },
  { id: 315, word: "Nibble", meaning: "To take small bites.", example: "She nibbled on the chocolate.", category: Category.HUMAN },
  { id: 316, word: "Pad", meaning: "To walk with quiet steps.", example: "He padded across in his socks.", category: Category.HUMAN },
  { id: 317, word: "Pat", meaning: "Touch quickly and gently with palm.", example: "She patted the dog.", category: Category.HUMAN },
  { id: 318, word: "Poop", meaning: "Feces.", example: "The dog did its poop.", category: Category.HUMAN },
  { id: 319, word: "Puke", meaning: "To vomit.", example: "He puked after drinking too much.", category: Category.HUMAN },
  { id: 320, word: "Retch", meaning: "The movement of vomiting.", example: "She retched but nothing came up.", category: Category.HUMAN },
  { id: 321, word: "Scratch", meaning: "Rub with fingernails.", example: "He scratched his head.", category: Category.HUMAN },
  { id: 322, word: "Scream", meaning: "Long loud piercing cry.", example: "She screamed at the spider.", category: Category.HUMAN },
  { id: 323, word: "Shout", meaning: "To say something very loudly.", example: "He shouted for help.", category: Category.HUMAN },
  { id: 324, word: "Shriek", meaning: "Loud high-pitched cry.", example: "The child shrieked with delight.", category: Category.HUMAN },
  { id: 325, word: "Shush", meaning: "To tell someone to be quiet.", example: "She shushed the noisy kids.", category: Category.HUMAN },
  { id: 326, word: "Slap", meaning: "Strike with the palm.", example: "He slapped the mosquito.", category: Category.HUMAN },
  { id: 327, word: "Slobber", meaning: "To let saliva flow; drool.", example: "The dog slobbered on the ball.", category: Category.HUMAN },
  { id: 328, word: "Smooch", meaning: "To kiss and cuddle.", example: "They smooched in the moonlight.", category: Category.HUMAN },
  { id: 329, word: "Sneak", meaning: "To move in a stealthy manner.", example: "He tried to sneak past the guard.", category: Category.HUMAN },
  { id: 330, word: "Sneer", meaning: "Smile with expressions of scorn.", example: "She sneered at his suggestion.", category: Category.HUMAN },
  { id: 331, word: "Sneeze", meaning: "Expel air forcibly from nose.", example: "He sneezed into his handkerchief.", category: Category.HUMAN },
  { id: 332, word: "Snicker", meaning: "Laugh in a half-suppressed way.", example: "She snickered at his joke.", category: Category.HUMAN },
  { id: 333, word: "Sniff", meaning: "Draw air audibly through nose.", example: "He sniffed the flowers.", category: Category.HUMAN },
  { id: 334, word: "Sniffle", meaning: "Sniff repeatedly because of a cold.", example: "She sniffled during the sad movie.", category: Category.HUMAN },
  { id: 335, word: "Snore", meaning: "Breathe with grunting sound asleep.", example: "He snored loudly.", category: Category.HUMAN },
  { id: 336, word: "Snort", meaning: "Exhale through nose expressing derision.", example: "He snorted in disbelief.", category: Category.HUMAN },
  { id: 337, word: "Sob", meaning: "Cry noisily with convulsive gasps.", example: "She sobbed at the news.", category: Category.HUMAN },
  { id: 338, word: "Spit", meaning: "Expel saliva from mouth.", example: "He spat out the seed.", category: Category.HUMAN },
  { id: 339, word: "Sputter", meaning: "Soft explosive sounds when heated.", example: "The bacon sputtered in the pan.", category: Category.HUMAN },
  { id: 340, word: "Stomp", meaning: "Tread heavily showing anger.", example: "He stomped out of the room.", category: Category.HUMAN },
  { id: 341, word: "Tap", meaning: "Strike lightly with tapping sound.", example: "She tapped her fingers.", category: Category.HUMAN },
  { id: 342, word: "Tattle", meaning: "Report others' wrongdoings.", example: "The child tattled on his brother.", category: Category.HUMAN },
  { id: 343, word: "Tiptoe", meaning: "Walk quietly on toes.", example: "She tiptoed into the room.", category: Category.HUMAN },
  { id: 344, word: "Utter", meaning: "To speak or pronounce.", example: "He uttered words of thanks.", category: Category.HUMAN },
  { id: 345, word: "Wail", meaning: "Prolonged high-pitched sound of grief.", example: "The mourners wailed.", category: Category.HUMAN },
  { id: 346, word: "Wallop", meaning: "Strike with great force.", example: "He walloped the ball.", category: Category.HUMAN },
  { id: 347, word: "Whack", meaning: "Strike forcefully with sharp blow.", example: "He whacked the fly.", category: Category.HUMAN },
  { id: 348, word: "Wheeze", meaning: "Breathe with whistling sound.", example: "He wheezed after the stairs.", category: Category.HUMAN },
  { id: 349, word: "Whimper", meaning: "Low weak sounds of fear.", example: "The puppy whimpered alone.", category: Category.HUMAN },
  { id: 350, word: "Whine", meaning: "Long high-pitched complaining cry.", example: "The child whined for candy.", category: Category.HUMAN },
  { id: 351, word: "Whisper", meaning: "Speak very softly.", example: "She whispered a secret.", category: Category.HUMAN },
  { id: 352, word: "Whistle", meaning: "High clear sound through lips.", example: "He whistled a tune.", category: Category.HUMAN },
  { id: 353, word: "Whoop", meaning: "Loud cry of joy.", example: "The children whooped with delight.", category: Category.HUMAN },
  { id: 354, word: "Wimper", meaning: "Variation of whimper.", example: "She wimpered remembering the movie.", category: Category.HUMAN },
  { id: 355, word: "Yack", meaning: "To talk incessantly.", example: "She yacked on the phone.", category: Category.HUMAN },
  { id: 356, word: "Yadda Yadda", meaning: "Meaningless talk.", example: "He went on, yadda yadda.", category: Category.HUMAN },
  { id: 357, word: "Yank", meaning: "Pull with sudden movement.", example: "He yanked the rope.", category: Category.HUMAN },
  { id: 358, word: "Yell", meaning: "Shout loudly from anger.", example: "He yelled for help.", category: Category.HUMAN },
  { id: 359, word: "Zonk", meaning: "Hit forcefully.", example: "He zonked the ball out.", category: Category.HUMAN },

  // Miscellaneous
  { id: 360, word: "Tick-tock", meaning: "The sound of a clock.", example: "The clock's tick-tock filled the room.", category: Category.MISC },
  { id: 361, word: "Hush", meaning: "A sound for silence.", example: "The teacher hushed the class.", category: Category.MISC },
  { id: 362, word: "Ahem", meaning: "Sound of clearing throat for attention.", example: "He gave an ahem before speaking.", category: Category.MISC },
  { id: 363, word: "Achoo", meaning: "Representation of a sneeze.", example: "She sneezed, 'achoo!'", category: Category.MISC },
  { id: 364, word: "Boo", meaning: "Express contempt or disapproval.", example: "The audience booed.", category: Category.MISC },
  { id: 365, word: "Brrr", meaning: "Sound made when feeling cold.", example: "'Brrr, it's cold!'", category: Category.MISC },
  { id: 366, word: "Eek", meaning: "Express fear or surprise.", example: "'Eek!' she cried at the spider.", category: Category.MISC },
  { id: 367, word: "Grrr", meaning: "Representation of a growl.", example: "The dog grrr-ed at the mailman.", category: Category.MISC },
  { id: 368, word: "Hmm", meaning: "Express hesitation or consideration.", example: "'Hmm,' she thought.", category: Category.MISC },
  { id: 369, word: "Mwah", meaning: "Sound of a kiss.", example: "She blew a kiss, 'mwah!'", category: Category.MISC },
  { id: 370, word: "Phew", meaning: "Express relief or exhaustion.", example: "'Phew, that was close!'", category: Category.MISC },
  { id: 371, word: "Tsk tsk", meaning: "Express disapproval or pity.", example: "'Tsk tsk, what a shame.'", category: Category.MISC }
];
